language: rust

rust:
  - nightly
  - beta
  - stable
  - 1.36.0

script:
  - cargo test

matrix:
  include:
    - rust: nightly
      os: osx
    - rust: nightly
      os: windows
  allow_failures:
    # macOS build temporarily disabled due to Cargo bug:
    # https://github.com/rust-lang/cargo/issues/7427
    - os: osx
