language: rust

rust:
  - nightly
  - beta
  - stable
  - 1.31.0

script:
  - cargo test

matrix:
  include:
    - rust: nightly
      os: osx
    - rust: nightly
      os: windows
    - rust: nightly
      name: Minimal versions
      script:
        - cargo update -Z minimal-versions
        - cargo check
